/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FoodServer_Restaurant;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.FoodServer.ServerRestaurantCustomerServiceOrganization;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import FeedbackAnalytics.DBOperation.DBOperator;
import FeedbackAnalytics.FeedbackProcessor.WordProcessor;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apple
 */
public class CustomerServiceJPanel extends javax.swing.JPanel {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    DBOperator dbOperator = new DBOperator();
    DefaultTableModel model;
    WordProcessor wp;
    List<String> stringList;

    JPanel userProcessContainer;
    EcoSystem business;
    UserAccount account;
    Enterprise enterprise;
    ServerRestaurantCustomerServiceOrganization organization;

    public CustomerServiceJPanel(JPanel userProcessContainer, UserAccount account, ServerRestaurantCustomerServiceOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.account = account;
        this.enterprise = enterprise;
        this.business = business;
        getDBFeedback();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFeedback = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtTargetProduct = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFeedBack = new javax.swing.JTextField();
        btnTraceBack = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Customer Service");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 28, -1, -1));

        tblFeedback.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblFeedback.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Customer Name", "FeedBack Property", "Target Product"
            }
        ));
        jScrollPane1.setViewportView(tblFeedback);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 89, 987, 218));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Target Product:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 441, -1, -1));

        txtTargetProduct.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtTargetProduct.setText("              ");
        txtTargetProduct.setEnabled(false);
        add(txtTargetProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 437, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("Feed Back:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 506, -1, -1));

        txtFeedBack.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtFeedBack.setText("                     ");
        txtFeedBack.setEnabled(false);
        add(txtFeedBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 506, 342, 96));

        btnTraceBack.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnTraceBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackAnalytics/Picture/back.png"))); // NOI18N
        btnTraceBack.setText("Trace Back >>");
        btnTraceBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraceBackActionPerformed(evt);
            }
        });
        add(btnTraceBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 443, -1, 54));

        btnView.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackAnalytics/Picture/order.png"))); // NOI18N
        btnView.setText("View Details");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(767, 316, -1, 77));

        btnSubmit.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackAnalytics/Picture/SubmitGreen.png"))); // NOI18N
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 533, 172, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnTraceBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraceBackActionPerformed
        TraceBackJPanel traceBackJPanel = new TraceBackJPanel(userProcessContainer, account, organization, enterprise, business);
        userProcessContainer.add("traceBackJPanel", traceBackJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnTraceBackActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void getDBFeedback() {
        DefaultTableModel model =dbOperator.getRestaurantFeedback(conn);
        tblFeedback.setModel(model);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnTraceBack;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFeedback;
    private javax.swing.JTextField txtFeedBack;
    private javax.swing.JTextField txtTargetProduct;
    // End of variables declaration//GEN-END:variables
}
