/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FoodServer_Restaurant;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.FoodProduce.ProducerProductOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author apple
 */
public class ManageInformationWorkArea extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem business;
    UserAccount account;
    Enterprise enterprise;
    Organization organization;
    
    public ManageInformationWorkArea(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.account = account;
        this.enterprise = enterprise;
        this.business = business;
        
    }
    
    public ManageInformationWorkArea(JPanel userProcessContainer,UserAccount account, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account=account;
        this.enterprise=enterprise;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtMessage1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAssignToCustomerService = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductList = new javax.swing.JTable();
        txtMessage2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnAssignToPurchase = new javax.swing.JButton();
        ComboProperty = new javax.swing.JComboBox<>();
        txtFeedBack = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Restaurant Manager Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 38, -1, -1));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Customer Name", "FeedBack Property", "Target Product"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 401, 474, 288));

        txtMessage1.setText("               ");
        add(txtMessage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 382, 220, 29));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Advise:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 379, -1, -1));

        btnAssignToCustomerService.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnAssignToCustomerService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackAnalytics/Picture/Assign.png"))); // NOI18N
        btnAssignToCustomerService.setText("Assign to Customer Service");
        add(btnAssignToCustomerService, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 429, -1, -1));

        tblProductList.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblProductList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product Name", "Quantity", "Producer Name", "Record Date"
            }
        ));
        jScrollPane2.setViewportView(tblProductList);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 130, 474, 205));

        txtMessage2.setText("               ");
        add(txtMessage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 133, 220, 29));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("Advise:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 130, -1, -1));

        btnAssignToPurchase.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnAssignToPurchase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackAnalytics/Picture/Assign.png"))); // NOI18N
        btnAssignToPurchase.setText("Assign to Purchaser");
        add(btnAssignToPurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 171, -1, -1));

        ComboProperty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Positive", "Negative" }));
        add(ComboProperty, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 344, -1, -1));

        txtFeedBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFeedBack.setText("                     ");
        txtFeedBack.setEnabled(false);
        add(txtFeedBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 529, 445, 119));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("Feed Back:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 529, -1, -1));

        btnSubmit.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackAnalytics/Picture/SubmitGreen.png"))); // NOI18N
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 666, 175, -1));

        btnBack.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackAnalytics/Picture/back.png"))); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 28, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
     userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboProperty;
    private javax.swing.JButton btnAssignToCustomerService;
    private javax.swing.JButton btnAssignToPurchase;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblProductList;
    private javax.swing.JTextField txtFeedBack;
    private javax.swing.JTextField txtMessage1;
    private javax.swing.JTextField txtMessage2;
    // End of variables declaration//GEN-END:variables
}
