/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FoodServer_Restaurant;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import userinterface.FoodServer_Restaurant.RestaurantPurchaserJPanel;
import userinterface.FoodServer_Restaurant.ManageInformationWorkArea;
import userinterface.FoodServer_Restaurant.CustomerServiceJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author apple
 */
public class RestaurantWorkArea extends javax.swing.JPanel {

   JPanel userProcessContainer;
    EcoSystem business;
    UserAccount account;
    Enterprise enterprise;
    Organization organization;
    
    public RestaurantWorkArea(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
    }

    
    public RestaurantWorkArea(JPanel userProcessContainer, UserAccount account, Organization FoodServerRestaurantAdminOrganization, Enterprise enterprise,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = FoodServerRestaurantAdminOrganization;
        this.account=account;
        this.enterprise=enterprise;
        this.business = business;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        btnRestaurantManager = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setText("My Work Area- Restaurant Service");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 54, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Restaurant");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 137, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 136, 143, 30));

        btnRestaurantManager.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnRestaurantManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackAnalytics/Picture/organization.png"))); // NOI18N
        btnRestaurantManager.setText("Restaurant Manager");
        btnRestaurantManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurantManagerActionPerformed(evt);
            }
        });
        add(btnRestaurantManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 268, 383, 77));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestaurantManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurantManagerActionPerformed
        ManagerWorkAreaJPanel3 managerWorkAreaPanel = new ManagerWorkAreaJPanel3(userProcessContainer,account,organization, enterprise, business);
        userProcessContainer.add("ManagerWorkAreaPanel", managerWorkAreaPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRestaurantManagerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRestaurantManager;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
