/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.SystemAdmin;

import Business.Business;
import Business.Customer;
import Business.Market;
import Business.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sunwe_000
 */
public class ManageMarketJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Business business;
    
    /**
     * Creates new form ManageMarketJPanel
     */

    ManageMarketJPanel(JPanel userProcessContainer, Business business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.business=business;
        populateMarketTable();
    }
    public void populateMarketTable()
    {
     DefaultTableModel dtm=(DefaultTableModel) tblMarket.getModel();
        dtm.setRowCount(0);
        int rowCount = dtm.getRowCount();
    for (int i = rowCount - 1; i >= 0; i--) {
         dtm.removeRow(i);
        }
    for (Market market : business.getMarketList().getMarketList())
    {
        Object[] row=new Object[2];
            row[0]=market;
            System.out.println(market);
            row[1]=String.valueOf(market.getCustomerList().size());
            dtm.addRow(row);
    }
    
    }
    
    public void populateCustomerTable(Market market)
    {
    DefaultTableModel dtm=(DefaultTableModel) tblViewCustomer.getModel();
        dtm.setRowCount(0);
        int rowCount = dtm.getRowCount();
    for (int i = rowCount - 1; i >= 0; i--) {
         dtm.removeRow(i);
        }
    for (Customer customer :market.getCustomerList())
    {
        Object[] row=new Object[3];
            row[0]=customer;
            row[1]=customer.getCustomerID();
            row[2]=String.valueOf(customer.getOrderHistory().size());
            dtm.addRow(row);
    }
    }
    /*
    *
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMarket = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblViewCustomer = new javax.swing.JTable();
        btnViewMarket = new javax.swing.JButton();
        txtMarketName = new javax.swing.JTextField();
        btnAddMarket = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        tblMarket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Market Name", "Number of Customer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMarket);
        if (tblMarket.getColumnModel().getColumnCount() > 0) {
            tblMarket.getColumnModel().getColumn(0).setResizable(false);
            tblMarket.getColumnModel().getColumn(1).setResizable(false);
        }

        tblViewCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Customer ID", "Number of History Order"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblViewCustomer);
        if (tblViewCustomer.getColumnModel().getColumnCount() > 0) {
            tblViewCustomer.getColumnModel().getColumn(0).setResizable(false);
            tblViewCustomer.getColumnModel().getColumn(1).setResizable(false);
            tblViewCustomer.getColumnModel().getColumn(2).setResizable(false);
        }

        btnViewMarket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnViewMarket.setText("Select and View");
        btnViewMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMarketActionPerformed(evt);
            }
        });

        txtMarketName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarketNameActionPerformed(evt);
            }
        });

        btnAddMarket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddMarket.setText("Add a Market");
        btnAddMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMarketActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewMarket))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMarketName, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(btnAddMarket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(179, 179, 179))
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarketName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMarketNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarketNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarketNameActionPerformed

    private void btnViewMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMarketActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMarket.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showConfirmDialog(null,"Please Select a Row to view details","Warning", JOptionPane.WARNING_MESSAGE);

        }
        else
        {
                Market market = (Market) tblMarket.getValueAt(selectedRow, 0);
                populateCustomerTable(market);
        }
    }//GEN-LAST:event_btnViewMarketActionPerformed

    private void btnAddMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMarketActionPerformed
        // TODO add your handling code here:
       try
       {
           int flag =0;
           String marketName=txtMarketName.getText();
       Pattern p1 = Pattern.compile("^[a-zA-Z]+$");
        Matcher m1 = p1.matcher(marketName);
          if(!m1.matches()) 
          {
          JOptionPane.showMessageDialog(null, "Please enter a valid input", "Error", JOptionPane.ERROR_MESSAGE);
                txtMarketName.setText("");
                flag=1;
          }
      
        else{
              
              int n=business.getMarketList().getMarketList().size();
              for(int i=0; i<n;i++)
              {
                  if(marketName.equalsIgnoreCase(business.getMarketList().getMarketList().get(i).getMarketName()))
                  {
                      JOptionPane.showMessageDialog(null, "Please enter a valid input", "Error", JOptionPane.ERROR_MESSAGE);
                       txtMarketName.setText("");
                       flag =1;
                      }
                  }
              }
          if(flag==0)
          {
          Market market = business.getMarketList().addMarket();
            market.setMarketName(marketName);
           populateMarketTable();
           txtMarketName.setText("");
           JOptionPane.showMessageDialog(null,"Successfully Created");
            
       }}
      catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Please enter correct data"); 
        }
    }//GEN-LAST:event_btnAddMarketActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMarket;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewMarket;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblMarket;
    private javax.swing.JTable tblViewCustomer;
    private javax.swing.JTextField txtMarketName;
    // End of variables declaration//GEN-END:variables
}
