/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FoodProduce;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.FoodProduce.ProducerProductOrganization;
import Business.Poultry.ChickenShed;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FoodProcess.PurchasingWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apple
 */
public class ManageProductionInformationJPanel2 extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount account;
    Enterprise enterprise;
    ProducerProductOrganization organization;
    EcoSystem system;

    /**
     * Creates new form ManageProductionInformationJPanel
     */
    public ManageProductionInformationJPanel2(JPanel userProcessContainer, UserAccount account, ProducerProductOrganization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        populateTable();
        populateAdvice();

    }

    public void populateAdvice() {
        if (organization.getWorkQueue().getWorkRequestList().size() != 0) {
            int a = organization.getWorkQueue().getWorkRequestList().size();
            WorkRequest req = organization.getWorkQueue().getWorkRequestList().get(a - 1);
            jLabel8.setText(String.valueOf(req.getMessage()));
        }
    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblProduction.getModel();
        dtm.setRowCount(0);
        int rowCount = dtm.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }

        for (ChickenShed u : system.getChickenShedDirectory().getChickenShedList()) {

            Object[] row = new Object[4];
            row[0] = u.getDate();
            row[1] = u;
            row[2] = u.getEggQuantity();
            row[3] = u.getEggType();
            dtm.addRow(row);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduction = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtEggQuantity = new javax.swing.JTextField();
        ComboState = new javax.swing.JComboBox();
        btnCreate = new javax.swing.JButton();
        txtChickenShedId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setBackground(new java.awt.Color(255, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Manage Production Information");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        tblProduction.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblProduction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "ChickenShed ID", "Egg Quantity", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProduction);
        if (tblProduction.getColumnModel().getColumnCount() > 0) {
            tblProduction.getColumnModel().getColumn(0).setResizable(false);
            tblProduction.getColumnModel().getColumn(1).setResizable(false);
            tblProduction.getColumnModel().getColumn(2).setResizable(false);
            tblProduction.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 630, 232));

        btnBack.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackAnalytics/Picture/back.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Date:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("ChickenShed Id:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("Egg Quantity:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setText("Type:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, -1, -1));

        txtDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 191, -1));

        txtEggQuantity.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtEggQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEggQuantityActionPerformed(evt);
            }
        });
        add(txtEggQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 191, -1));

        ComboState.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ComboState.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "High", "Medium", "Low" }));
        ComboState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboStateActionPerformed(evt);
            }
        });
        add(ComboState, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, 191, -1));

        btnCreate.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackAnalytics/Picture/SubmitGreen.png"))); // NOI18N
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 510, 180, -1));

        txtChickenShedId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtChickenShedId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChickenShedIdActionPerformed(evt);
            }
        });
        add(txtChickenShedId, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 191, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 204));
        jLabel6.setText("Manager Advise:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, -1, -1));

        jLabel8.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, -1, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void txtEggQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEggQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEggQuantityActionPerformed

    private void ComboStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboStateActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:

        try {

            Pattern p1 = Pattern.compile("^(0?[1-9]|[12][0-9]|3[01])[\\/\\-](0?[1-9]|1[012])[\\/\\-]\\d{4}$");
            Pattern p2 = Pattern.compile("^[0-9]+$");
            Matcher m1 = p1.matcher(txtDate.getText());
            Matcher m2 = p2.matcher(txtChickenShedId.getText());
            Matcher m3 = p2.matcher(txtEggQuantity.getText());
            if (!m1.matches() || !m2.matches() || !m3.matches()) {
                JOptionPane.showMessageDialog(null, "Please enter a valid input", "Error", JOptionPane.ERROR_MESSAGE);
                txtDate.setText("");
                txtChickenShedId.setText("");
                txtEggQuantity.setText("");
            } else {
                ChickenShed shed = system.getChickenShedDirectory().addChickenShed();
                shed.setDate(txtDate.getText());
                shed.setChickenShedId(Integer.parseInt(txtChickenShedId.getText()));
                shed.setEggQuantity(Integer.parseInt(txtEggQuantity.getText()));
                shed.setEggType(String.valueOf(ComboState.getSelectedItem()));
                populateTable();
                JOptionPane.showMessageDialog(null, "Production Table updated");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter correct data");
        }


    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtChickenShedIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChickenShedIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChickenShedIdActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboState;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProduction;
    private javax.swing.JTextField txtChickenShedId;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEggQuantity;
    // End of variables declaration//GEN-END:variables
}
