/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FoodProduce;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.FoodProduce.ProducerProductOrganization;
import Business.Organization.FoodProduce.ProducerSterelizationOrganization;
import Business.Organization.Organization;
import Business.Poultry.ChickenShed;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FoodProcess.PurchasingWorkRequest;
import Business.WorkQueue.FoodProduce.ProductionWorkRequest;
import Business.WorkQueue.FoodProduce.SterelizationWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import static userinterface.FoodProduce.ManageOrderJPanel2.producersalesorganization;

/**
 *
 * @author apple
 */
public class ManageInformationJPanel5 extends javax.swing.JPanel {
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount account;
    Enterprise enterprise;
    Organization organization;
    /**
     * Creates new form ManageInformationJPanel
     */
    public ManageInformationJPanel5(JPanel userProcessContainer,UserAccount account, Enterprise enterprise, EcoSystem system, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.account = account;
        this.enterprise = enterprise;
        this.organization = producersalesorganization;
        populateTable1();
        populateTable2();
        populateTable3();
        
    }
public void populateTable1()
    {
       DefaultTableModel dtm=(DefaultTableModel) tblProduction.getModel();
        dtm.setRowCount(0);
        int rowCount = dtm.getRowCount();
    for (int i = rowCount - 1; i >= 0; i--) {
         dtm.removeRow(i);
        }
        
        for(ChickenShed u: system.getChickenShedDirectory().getChickenShedList())
        {
            
            
            Object[] row=new Object[4];
            row[0]=u.getDate();
            row[1]=u;
            row[2]=u.getEggQuantity();
            row[3]=u.getEggType();
            dtm.addRow(row);
            
        }
    }
        
        public void populateTable2()
    {
       DefaultTableModel dtm=(DefaultTableModel) tblSterilization.getModel();
        dtm.setRowCount(0);
        int rowCount = dtm.getRowCount();
    for (int i = rowCount - 1; i >= 0; i--) {
         dtm.removeRow(i);
        }
        
        for(ChickenShed u: system.getChickenShedDirectory().getChickenShedList())
        {
            
            
            Object[] row=new Object[6];
            row[0]=u;
            row[1]=u.getHumidity();
            row[2]=u.getTemperature();
            row[3]=u.getWeatheroutside();
            row[4]=u.getIsSterelized();
            row[5]=u.getStatus();
            dtm.addRow(row);
            
        }
    }
        public void populateTable3()
    {
       DefaultTableModel dtm = (DefaultTableModel) tblProduct.getModel();
        dtm.setRowCount(0);
        int rowCount = dtm.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }

        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[5];
            row[0] = ((PurchasingWorkRequest) request);
            row[1] = ((PurchasingWorkRequest) request).getQuantity();
            row[2] = ((PurchasingWorkRequest) request).getProducerName();
            row[3] = ((PurchasingWorkRequest) request).getDate();
            String result = ((PurchasingWorkRequest) request).getStatus();
            row[4] = result == null ? "Waiting" : result;

            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduction = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSterilization = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtProductionAdvice = new javax.swing.JTextField();
        btnAssignToProduction = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtSterelizationAdvice = new javax.swing.JTextField();
        btnAssignToSales = new javax.swing.JButton();
        txtSalesAdvice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnAssignToSterlization = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Manage Information");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 23, -1, -1));

        btnBack.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackAnalytics/Picture/back.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 13, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Production:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 135, -1, -1));

        tblProduction.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblProduction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "ChickenShed ID", "Egg Quanitity", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProduction);
        if (tblProduction.getColumnModel().getColumnCount() > 0) {
            tblProduction.getColumnModel().getColumn(0).setResizable(false);
            tblProduction.getColumnModel().getColumn(1).setResizable(false);
            tblProduction.getColumnModel().getColumn(2).setResizable(false);
            tblProduction.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 141, 901, 93));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Sterilization:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 363, -1, -1));

        tblSterilization.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblSterilization.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ChickenShed ID", "Humidity", "Tempreture", "Weather", "If Steriization", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSterilization);
        if (tblSterilization.getColumnModel().getColumnCount() > 0) {
            tblSterilization.getColumnModel().getColumn(0).setResizable(false);
            tblSterilization.getColumnModel().getColumn(1).setResizable(false);
            tblSterilization.getColumnModel().getColumn(2).setResizable(false);
            tblSterilization.getColumnModel().getColumn(3).setResizable(false);
            tblSterilization.getColumnModel().getColumn(4).setResizable(false);
            tblSterilization.getColumnModel().getColumn(5).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 363, 901, 96));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setText("Sales:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 576, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setText("Advise:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 259, -1, -1));

        txtProductionAdvice.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add(txtProductionAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 258, 220, 29));

        btnAssignToProduction.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnAssignToProduction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackAnalytics/Picture/Assign.png"))); // NOI18N
        btnAssignToProduction.setText("Assign to Production Section");
        btnAssignToProduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToProductionActionPerformed(evt);
            }
        });
        add(btnAssignToProduction, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 252, 558, 57));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setText("Advise:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 478, -1, -1));

        txtSterelizationAdvice.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add(txtSterelizationAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 477, 220, 29));

        btnAssignToSales.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnAssignToSales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackAnalytics/Picture/Assign.png"))); // NOI18N
        btnAssignToSales.setText("          Assign to Sales Section");
        add(btnAssignToSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 734, 558, -1));

        txtSalesAdvice.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtSalesAdvice.setText("               ");
        add(txtSalesAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 732, 220, 29));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setText("Advise:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 733, -1, -1));

        btnAssignToSterlization.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnAssignToSterlization.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackAnalytics/Picture/Assign.png"))); // NOI18N
        btnAssignToSterlization.setText("Assign to Sterelization Section");
        btnAssignToSterlization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToSterlizationActionPerformed(evt);
            }
        });
        add(btnAssignToSterlization, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 477, 560, -1));

        tblProduct.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Quantity", "Producer Name", "Record Date", "Status"
            }
        ));
        jScrollPane3.setViewportView(tblProduct);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 576, 911, 123));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignToSterlizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToSterlizationActionPerformed
        // TODO add your handling code here:
        String message = txtSterelizationAdvice.getText();
        
        SterelizationWorkRequest request = new SterelizationWorkRequest();
        request.setMessage(message);
        request.setSender(account);
        request.setStatus("Sent");
        
        Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof ProducerSterelizationOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
        }
    }//GEN-LAST:event_btnAssignToSterlizationActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAssignToProductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToProductionActionPerformed
        // TODO add your handling code here:
      String message = txtProductionAdvice.getText();
        
        ProductionWorkRequest request = new ProductionWorkRequest();
        request.setMessage(message);
        request.setSender(account);
        request.setStatus("Sent");
        
        Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof ProducerProductOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
        }
    }//GEN-LAST:event_btnAssignToProductionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignToProduction;
    private javax.swing.JButton btnAssignToSales;
    private javax.swing.JButton btnAssignToSterlization;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTable tblProduction;
    private javax.swing.JTable tblSterilization;
    private javax.swing.JTextField txtProductionAdvice;
    private javax.swing.JTextField txtSalesAdvice;
    private javax.swing.JTextField txtSterelizationAdvice;
    // End of variables declaration//GEN-END:variables
}
