/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FoodProduce;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.FoodProduce.ProducerProductOrganization;
import Business.Organization.FoodProduce.ProducerSalesOrganization;
import Business.Poultry.ChickenShed;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FoodProcess.PurchasingWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apple
 */
public class ManageOrderJPanel2 extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount account;
    Enterprise enterprise;
    public static ProducerSalesOrganization producersalesorganization;
    EcoSystem system;

    /**
     * Creates new form ManageOrderJPanel2
     */
    public ManageOrderJPanel2(JPanel userProcessContainer, UserAccount account, ProducerSalesOrganization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.producersalesorganization = organization;
        this.enterprise = enterprise;
        this.system = system;
        populateTable();
        populateAdvice();

    }

    public void populateAdvice() {
        if (producersalesorganization.getWorkQueue().getWorkRequestList().size() != 0) {
            int a = producersalesorganization.getWorkQueue().getWorkRequestList().size();
            WorkRequest req = producersalesorganization.getWorkQueue().getWorkRequestList().get(a - 1);
            labAdvice.setText(String.valueOf(req.getMessage()));
        }
    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblProduct.getModel();
        dtm.setRowCount(0);
        int rowCount = dtm.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }

        for (WorkRequest request : producersalesorganization.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[5];
            row[0] = ((PurchasingWorkRequest) request);
            row[1] = ((PurchasingWorkRequest) request).getQuantity();
            row[2] = ((PurchasingWorkRequest) request).getProducerName();
            row[3] = ((PurchasingWorkRequest) request).getDate();
            String result = ((PurchasingWorkRequest) request).getStatus();
            row[4] = result == null ? "Waiting" : result;

            dtm.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ComboState = new javax.swing.JComboBox();
        btnCreate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        labAdvice = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackAnalytics/Picture/back.png"))); // NOI18N
        btnBack.setText(" Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Manage Order");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Date:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, -1, -1));

        txtDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 191, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setText("State:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, -1, -1));

        ComboState.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ComboState.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selected", "Pending", "Completed" }));
        ComboState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboStateActionPerformed(evt);
            }
        });
        add(ComboState, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, 191, -1));

        btnCreate.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackAnalytics/Picture/modify.png"))); // NOI18N
        btnCreate.setText("Modify");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, -1, -1));

        tblProduct.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Quantity", "Producer Name", "Record Date", "Status"
            }
        ));
        jScrollPane2.setViewportView(tblProduct);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 660, 370));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 153));
        jLabel9.setText("Manager Advise:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 640, -1, -1));

        labAdvice.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        add(labAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void ComboStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboStateActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        try {

            Pattern p1 = Pattern.compile("^(0?[1-9]|[12][0-9]|3[01])[\\/\\-](0?[1-9]|1[012])[\\/\\-]\\d{4}$");
            Matcher m1 = p1.matcher(txtDate.getText());

            if (!m1.matches()) {
                JOptionPane.showMessageDialog(null, "Please enter a valid input", "Error", JOptionPane.ERROR_MESSAGE);
                txtDate.setText(""); 
            } else {
                int selectedRow = tblProduct.getSelectedRow();

                if (selectedRow < 0) {
                    return;
                }

                PurchasingWorkRequest request = (PurchasingWorkRequest) tblProduct.getValueAt(selectedRow, 0);
                request.setDate(txtDate.getText());
                request.setStatus(String.valueOf(ComboState.getSelectedItem()));
                populateTable();

                JOptionPane.showMessageDialog(null, "Order Processed");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter correct data");
        }

    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboState;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labAdvice;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextField txtDate;
    // End of variables declaration//GEN-END:variables
}
