/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FoodProduce;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.FoodProduce.ProducerProductOrganization;
import Business.Organization.FoodProduce.ProducerSterelizationOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author apple
 */
public class SterilizationWorkAreaJPanel1 extends javax.swing.JPanel {
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount account;
    Enterprise enterprise;
    ProducerSterelizationOrganization organization;
    /**
     * Creates new form SterilizationWorkAreaJPanel1
     */
    public SterilizationWorkAreaJPanel1(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
    }

    public SterilizationWorkAreaJPanel1(JPanel userProcessContainer, UserAccount account, ProducerSterelizationOrganization organization, Enterprise enterprise,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.account=account;
        this.enterprise=enterprise;
        this.system = system;
        System.out.println(account);
        System.out.println(enterprise);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSterilizationProcess = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Sterilization Staff Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 55, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 134, -1, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Producer");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 135, -1, -1));

        btnSterilizationProcess.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnSterilizationProcess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackAnalytics/Picture/Sterilization.png"))); // NOI18N
        btnSterilizationProcess.setText("Manage Sterilization Process");
        btnSterilizationProcess.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSterilizationProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSterilizationProcessActionPerformed(evt);
            }
        });
        add(btnSterilizationProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 248, -1, -1));

        btnBack.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackAnalytics/Picture/back.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.setToolTipText("");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 45, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSterilizationProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSterilizationProcessActionPerformed
        // TODO add your handling code here:
        ManageSterilizationProcessJPanel2 manageSterProcess = new ManageSterilizationProcessJPanel2(userProcessContainer,account,organization,enterprise,system);
        userProcessContainer.add("manageSterProcess", manageSterProcess);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnSterilizationProcessActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSterilizationProcess;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
