/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.FoodServer_Market;

/**
 *
 * @author apple
 */
public class ManageCustomerFeedBackJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomerFeedBackJPanel
     */
    public ManageCustomerFeedBackJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblComment = new javax.swing.JTable();
        btnPickUp = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSubmit = new javax.swing.JButton();
        ComboSupermarket = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Manage Customer Feedback");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 49, -1, -1));

        tblComment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Date", "Comment", "Properties"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblComment);
        if (tblComment.getColumnModel().getColumnCount() > 0) {
            tblComment.getColumnModel().getColumn(0).setResizable(false);
            tblComment.getColumnModel().getColumn(1).setResizable(false);
            tblComment.getColumnModel().getColumn(2).setResizable(false);
            tblComment.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 138, 779, 224));

        btnPickUp.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnPickUp.setText("Pick up Core Meaning");
        add(btnPickUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 388, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Content", "Properties"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 441, 779, 244));

        btnSubmit.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnSubmit.setText("Submit");
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(849, 694, -1, -1));

        ComboSupermarket.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ComboSupermarket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(ComboSupermarket, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 62, -1, -1));

        btnBack.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackAnalytics/Picture/back.png"))); // NOI18N
        btnBack.setText("Back");
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 39, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboSupermarket;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPickUp;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblComment;
    // End of variables declaration//GEN-END:variables
}
