/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FoodServer_Market;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.FoodServer_Restaurant.ManageEmployeeJPanel;
import userinterface.FoodServer_Restaurant.ManageOrganizationJPanel;

/**
 *
 * @author apple
 */
public class MarketWorkArea extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem system;
    Organization organization;
    Enterprise enterprise;
    UserAccount account;

    public MarketWorkArea(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = business;
        this.organization = organization;
        this.enterprise = enterprise;
        this.account = account;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnUser = new javax.swing.JButton();
        btnEmployee = new javax.swing.JButton();
        btnOrg = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setForeground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setText("My Work Area- Market Service");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 53, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 137, 148, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Market");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 138, -1, -1));

        btnUser.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackAnalytics/Picture/useraccount.png"))); // NOI18N
        btnUser.setText("       Market User");
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });
        add(btnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 458, 331, 68));

        btnEmployee.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackAnalytics/Picture/user.png"))); // NOI18N
        btnEmployee.setText("Market Employee");
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });
        add(btnEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 326, 331, 75));

        btnOrg.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnOrg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackAnalytics/Picture/organization.png"))); // NOI18N
        btnOrg.setText("Market Organization");
        btnOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrgActionPerformed(evt);
            }
        });
        add(btnOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 215, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
         MarketManageEmployee  marketManageEmployeeJPanel = new MarketManageEmployee(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("marketManageEmployeeJPanel", marketManageEmployeeJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnEmployeeActionPerformed

    private void btnOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrgActionPerformed
        MarketManageOrganization marketManageOrganization = new MarketManageOrganization(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("marketManageOrganization", marketManageOrganization);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnOrgActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        MarketManageUser  marketManageUserJPanel = new MarketManageUser(userProcessContainer, enterprise,system);
        userProcessContainer.add("marketManageUserJPanel", marketManageUserJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnOrg;
    private javax.swing.JButton btnUser;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
