/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FoodProcess;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.ProcessedProduct.StorageProduct;
import Business.ProcessedProduct.StorageProductDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Business.storageclass.Product;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apple
 */
public class StorageStaff extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount account;
    Enterprise enterprise;
    Organization organization;

    /**
     * Creates new form StorageStaff
     */
    public StorageStaff(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = business;
        this.account = account;
        this.enterprise = enterprise;
        this.organization = organization;
        System.out.println(organization);
        System.out.println(account);
        System.out.println(enterprise);
        populateTable();
        populateAdvice();
    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblStorageStaff.getModel();
        dtm.setRowCount(0);

        for (Product sp : system.getProductdirectory().getProductlist()) {

            Object[] row = new Object[5];
            row[0] = sp.getProducerName();
            row[1] = sp;
            row[2] = sp.getQuantity();
            row[3] = sp.getTemperature();
            row[4] = sp.getHumidity();
            dtm.addRow(row);

        }

    }

    public void populateAdvice() {
        if (organization.getWorkQueue().getWorkRequestList().size() != 0) 
        {
            int a = organization.getWorkQueue().getWorkRequestList().size();
            WorkRequest req = organization.getWorkQueue().getWorkRequestList().get(a - 1);
            lbAdvice2.setText(String.valueOf(req.getMessage()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStorageStaff = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTempreture = new javax.swing.JTextField();
        txtHumidity = new javax.swing.JTextField();
        txtSetParameter = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbAdvice2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Storage Staff Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 57, -1, -1));

        tblStorageStaff.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tblStorageStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producer Name", "Product Name", "Quantity", "Tempreture", "Humidity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblStorageStaff);
        if (tblStorageStaff.getColumnModel().getColumnCount() > 0) {
            tblStorageStaff.getColumnModel().getColumn(0).setResizable(false);
            tblStorageStaff.getColumnModel().getColumn(1).setResizable(false);
            tblStorageStaff.getColumnModel().getColumn(2).setResizable(false);
            tblStorageStaff.getColumnModel().getColumn(3).setResizable(false);
            tblStorageStaff.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 166, 746, 312));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setText("Tempreture:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 507, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setText("Humidity:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 558, -1, -1));

        txtTempreture.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add(txtTempreture, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 503, 133, -1));

        txtHumidity.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add(txtHumidity, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 554, 133, -1));

        txtSetParameter.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtSetParameter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackAnalytics/Picture/set.png"))); // NOI18N
        txtSetParameter.setText("Set Parameters");
        txtSetParameter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtSetParameter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSetParameterActionPerformed(evt);
            }
        });
        add(txtSetParameter, new org.netbeans.lib.awtextra.AbsoluteConstraints(731, 514, 252, 69));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 153));
        jLabel2.setText("Manager Advise:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 651, -1, -1));

        lbAdvice2.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        add(lbAdvice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 689, -1, -1));

        btnBack.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedbackAnalytics/Picture/back.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 166, -1, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void txtSetParameterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSetParameterActionPerformed
        // TODO add your handling code here:
         try {

            Pattern p1 = Pattern.compile("^[0-9]+$");
            Matcher m1 = p1.matcher(txtHumidity.getText());
            Matcher m2 = p1.matcher(txtTempreture.getText());
              if (!m1.matches() || !m2.matches()) {
                JOptionPane.showMessageDialog(null, "Please enter a valid input", "Error", JOptionPane.ERROR_MESSAGE);
                txtHumidity.setText("");
                txtTempreture.setText("");
                } else {
                   int selectedRow = tblStorageStaff.getSelectedRow();
                
                if (selectedRow < 0) {
                    return;
                }
                
                Product product = (Product) tblStorageStaff.getValueAt(selectedRow, 1);
            
            product.setHumidity(Integer.parseInt(txtHumidity.getText()));
            product.setTemperature(Integer.parseInt(txtTempreture.getText()));
            populateTable();
              JOptionPane.showMessageDialog(null, "Storage Data Successfully Created");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter correct data");
        }
    }//GEN-LAST:event_txtSetParameterActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAdvice2;
    private javax.swing.JTable tblStorageStaff;
    private javax.swing.JTextField txtHumidity;
    private javax.swing.JButton txtSetParameter;
    private javax.swing.JTextField txtTempreture;
    // End of variables declaration//GEN-END:variables
}
